
services:
  - type: web
    name: fracturestudio
    env: node
    buildCommand: yarn && yarn build
    startCommand: yarn start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        src: /*
        dest: /index.html
